version: '3.7'

services:
  django-files:
    image: ghcr.io/django-files/django-files:latest
    env_file: ${ENV_FILE}
    deploy:
      mode: global
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.df-shane-http.rule=Host(`${TRAEFIK_HOST:-}`)"
        - "traefik.http.routers.df-shane-http.entrypoints=http"
        - "traefik.http.routers.df-shane-http.middlewares=https-redirect"
        - "traefik.http.routers.df-shane-https.rule=Host(`${TRAEFIK_HOST:-}`)"
        - "traefik.http.routers.df-shane-https.entrypoints=https"
        - "traefik.http.routers.df-shane-https.tls=true"
        - "traefik.http.services.df-shane.loadbalancer.server.port=80"
        - "traefik.http.services.df-shane.loadbalancer.server.scheme=http"
    volumes:
      - media_dir:/data/media
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true

volumes:
  media_dir:
